---
title: "Appendix A: Random community change"
toc: no
output:
  bookdown::pdf_document2
---

```{r settings, echo = FALSE, message=FALSE, cache=FALSE}
source("R/Settings.R")
```

# Introduction and mehtods {-}
Add text to explain the ideas and methods.

Auch noch auf Interaktion texten:
```{r}
library(arm)

res1 <- rbind(
  tres %>% transmute(aID_STAO = aID_STAO, Sitemeasure = Sitemeasure, mean = mean, type = "Sample"),
  tres %>% transmute(aID_STAO = aID_STAO, Sitemeasure = Sitemeasure, mean = meanreal, type = "Real"))
mod1 <- lmer(mean ~ Sitemeasure * type + (1|aID_STAO), data = res1)
mod2 <- lmer(mean ~ Sitemeasure + type + (1|aID_STAO), data = res1)
anova(mod1, mod2)


summary(glmer(SR ~ yr * NTOT + (yr|aID_STAO), data = surv, family = "poisson"))
mod1 <- lmer(N ~ yr * NTOT + (yr|aID_STAO), data = surv)
mod2 <- lmer(N ~ yr + NTOT + (yr|aID_STAO), data = surv)
anova(mod1, mod2)


los <- tibble()
gain <- tibble()
T <- tibble()

library(arm)
los$ef <- los$meanreal - los$mean
summary(lmer(ef ~ EL * Sitemeasure + (1|aID_STAO), data = los))

gain$ef <- gain$meanreal - gain$mean
summary(lmer(ef ~ EL * Sitemeasure + (1|aID_STAO), data = gain))

T$ef <- T$meanreal - T$mean
mod1 <- lmer(ef ~ type + (1|aID_STAO), data = T)
mod2 <- lmer(ef ~ 1 + (1|aID_STAO), data = T)
anova(mod1, mod2)
```


# Results {-}

```{r Tplot, fig.cap="\\textit{Average Ellenberg value for \\textbf{temperature} of lost (A) and newly appearing (B) species compared to the same number of species that were randomly selected from all species recorded at the sample site (i.e. random communities). Crosses indicate the community mean of lost and newly appearing species; the grey vertical lines indicate the range of the 5\\% and 95\\% quantiles of community means calculated from the 1000 random communities for each site. The curves show the regression lines with third order polynomials for the community means of lost and newly appearing species (black solid lines) and for the average community means of random communities (orange dotted lines).}"}
# Make calculations and plot for Ellenberg T value
tres <- makesim(EL = "T", gain = FALSE, sitem = "Temperature")

tres$EL <- "T"; los <- rbind(los, tres)
tres$type <- "loss"; T <- rbind(T, tres)

txlab <- seq(0, 100, 10)
tylab <- seq(1, 5, 0.5)
ploss <- ggplot(tres, aes(x = Sitemeasure, y = meanreal)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), lwd = 0.5, colour = "grey80") +
  geom_point(shape = 4, colour = "black", cex = 2) +
  stat_smooth(method = "lm", formula = y ~ poly(x, 3), se = FALSE, col = "black") +
  stat_smooth(aes(y = mean), method = "lm", formula = y ~ poly(x,3), se = FALSE, col = "orange", lty = 2) +
  scale_x_continuous(breaks = (txlab - 50) / 10, labels = txlab / 10, limits = c(-1, NA)) +
  scale_y_continuous(breaks = tylab, labels = tylab, limits = c(2, 4)) +
  labs(x = "Annual mean temperature", y = "Ellenberg temperature value\n(community mean)",
       title = "(A) Species losses") 
tres <- makesim(EL = "T", gain = TRUE, sitem = "Temperature")
tres$EL <- "T"; gain <- rbind(gain, tres)
tres$type <- "gain"; T <- rbind(T, tres)

pgain <- ggplot(tres, aes(x = Sitemeasure, y = meanreal)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), lwd = 0.5, colour = "grey80") +
  geom_point(shape = 4, colour = "black", cex = 2) +
  stat_smooth(method = "lm", formula = y ~ poly(x, 3), se = FALSE, col = "black") +
  stat_smooth(aes(y = mean), method = "lm", formula = y ~ poly(x,3), se = FALSE, col = "orange", lty = 2) +
  scale_x_continuous(breaks = (txlab - 50) / 10, labels = txlab/10, limits = c(-1, NA)) +
  scale_y_continuous(breaks = (tylab - 3), labels = tylab, limits = c(-1, 1)) +
  labs(x = "Annual mean temperature", y = "Ellenberg temperature value\n(community mean)",
       title = "(B) Species gains") 
multiplot(ploss, pgain, cols = 2)
```

```{r Fplot, fig.cap="\\textit{Average Ellenberg value for \\textbf{humidity} of lost (A) and newly appearing (B) species compared to the same number of species that were randomly selected from all species recorded at the sample site (i.e. random communities). Crosses indicate the community mean of lost and newly appearing species; the grey vertical lines indicate the range of the 5\\% and 95\\% quantiles of community means calculated from the 1000 random communities for each site. The curves show the regression lines with third order polynomials for the community means of lost and newly appearing species (black solid lines) and for the average community means of random communities (orange dotted lines).}"}
# Make calculations and plot for Ellenberg F value
tres <- makesim(EL = "F", gain = FALSE, sitem = "Precipitation")
txlab <- seq(800, 2000, 200)
tylab <- seq(1, 4, 0.5)
ploss <- ggplot(tres, aes(x = Sitemeasure, y = meanreal)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), lwd = 0.5, colour = "grey80") +
  geom_point(shape = 4, colour = "black", cex = 2) +
  stat_smooth(method = "lm", formula = y ~ poly(x, 3), se = FALSE, col = "black") +
  stat_smooth(aes(y = mean), method = "lm", formula = y ~ poly(x,3), se = FALSE, col = "orange", lty = 2) +
  scale_x_continuous(breaks = (txlab - 1000) / 200, labels = txlab, limits = c(-1, NA)) +
  scale_y_continuous(breaks = (tylab - 3), labels = tylab, limits = c(-1, 1)) +
  labs(x = "Annual mean precipitation", y = "Ellenberg humidity value\n(community mean)",
       title = "(A) Species losses") 
tres <- makesim(EL = "F", gain = TRUE, sitem = "Precipitation")
pgain <- ggplot(tres, aes(x = Sitemeasure, y = meanreal)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), lwd = 0.5, colour = "grey80") +
  geom_point(shape = 4, colour = "black", cex = 2) +
  stat_smooth(method = "lm", formula = y ~ poly(x, 3), se = FALSE, col = "black") +
  stat_smooth(aes(y = mean), method = "lm", formula = y ~ poly(x,3), se = FALSE, col = "orange", lty = 2) +
  scale_x_continuous(breaks = (txlab - 1000) / 200, labels = txlab, limits = c(-1, NA)) +
  scale_y_continuous(breaks = (tylab - 3), labels = tylab, limits = c(-1, 1)) +
  labs(x = "Annual mean precipitation", y = "Ellenberg humidity value\n(community mean)",
       title = "(B) Species gains") 
multiplot(ploss, pgain, cols = 2)
```

```{r Nplot, fig.cap="\\textit{Average Ellenberg value for \\textbf{nutrients} of lost (A) and newly appearing (B) species compared to the same number of species that were randomly selected from all species recorded at the sample site (i.e. random communities). Crosses indicate the community mean of lost and newly appearing species; the grey vertical lines indicate the range of the 5\\% and 95\\% quantiles of community means calculated from the 1000 random communities for each site. The curves show the regression lines with third order polynomials for the community means of lost and newly appearing species (black solid lines) and for the average community means of random communities (orange dotted lines).}"}
# Make calculations and plot for Ellenberg N value
tres <- makesim(EL = "N", gain = FALSE, sitem = "NTOT")
tres$EL <- "N"; los <- rbind(los, tres)
txlab <- seq(0, 40, 5)
tylab <- seq(1, 4, 0.5)
ploss <- ggplot(tres, aes(x = Sitemeasure, y = meanreal)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), lwd = 0.5, colour = "grey80") +
  geom_point(shape = 4, colour = "black", cex = 2) +
  stat_smooth(method = "lm", formula = y ~ poly(x, 3), se = FALSE, col = "black") +
  stat_smooth(aes(y = mean), method = "lm", formula = y ~ poly(x,3), se = FALSE, col = "orange", lty = 2) +
  scale_x_continuous(breaks = (txlab - 10) / 10, labels = txlab, limits = c(-1, NA)) +
  scale_y_continuous(breaks = (tylab - 3), labels = tylab, limits = c(-1.2, 1)) +
  labs(x = "Nitrogen deposition", y = "Ellenberg nutrient value\n(community mean)",
       title = "(A) Species losses") 
tres <- makesim("N", gain = TRUE, sitem = "NTOT")
tres$EL <- "N"; gain <- rbind(gain, tres)
pgain <- ggplot(tres, aes(x = Sitemeasure, y = meanreal)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), lwd = 0.5, colour = "grey80") +
  geom_point(shape = 4, colour = "black", cex = 2) +
  stat_smooth(method = "lm", formula = y ~ poly(x, 3), se = FALSE, col = "black") +
  stat_smooth(aes(y = mean), method = "lm", formula = y ~ poly(x,3), se = FALSE, col = "orange", lty = 2) +
  scale_x_continuous(breaks = (txlab - 10) / 10, labels = txlab, limits = c(-1, NA)) +
  scale_y_continuous(breaks = tylab, labels = tylab, limits = c(1.8, 4)) +
  labs(x = "Nitrogen deposition", y = "Ellenberg nutrient value\n(community mean)",
       title = "(B) Species gains") 
multiplot(ploss, pgain, cols = 2)
```

```{r Lplot, fig.cap="\\textit{Average Ellenberg value for \\textbf{light} of lost (A) and newly appearing (B) species compared to the same number of species that were randomly selected from all species recorded at the sample site (i.e. random communities). Crosses indicate the community mean of lost and newly appearing species; the grey vertical lines indicate the range of the 5\\% and 95\\% quantiles of community means calculated from the 1000 random communities for each site. The curves show the regression lines with third order polynomials for the community means of lost and newly appearing species (black solid lines) and for the average community means of random communities (orange dotted lines).}"}
# Make calculations and plot for Ellenberg N value
tres <- makesim(EL = "L", gain = FALSE, sitem = "Inclination")
txlab <- seq(0, 60, 10)
tylab <- seq(1, 5, 0.5)
ploss <- ggplot(tres, aes(x = Sitemeasure, y = meanreal)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), lwd = 0.5, colour = "grey80") +
  geom_point(shape = 4, colour = "black", cex = 2) +
  stat_smooth(method = "lm", formula = y ~ poly(x, 3), se = FALSE, col = "black") +
  stat_smooth(aes(y = mean), method = "lm", formula = y ~ poly(x,3), se = FALSE, col = "orange", lty = 2) +
  scale_x_continuous(breaks = (txlab - 10) / 10, labels = txlab, limits = c(-1, NA)) +
  scale_y_continuous(breaks = (tylab - 3), labels = tylab, limits = c(-0.5, 1.5)) +
  labs(x = "Inclination", y = "Ellenberg light value\n(community mean)",
       title = "(A) Species losses") 
tres <- makesim("L", gain = TRUE, sitem = "Inclination")
pgain <- ggplot(tres, aes(x = Sitemeasure, y = meanreal)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), lwd = 0.5, colour = "grey80") +
  geom_point(shape = 4, colour = "black", cex = 2) +
  stat_smooth(method = "lm", formula = y ~ poly(x, 3), se = FALSE, col = "black") +
  stat_smooth(aes(y = mean), method = "lm", formula = y ~ poly(x,3), se = FALSE, col = "orange", lty = 2) +
  scale_x_continuous(breaks = (txlab - 10) / 10, labels = txlab, limits = c(-1, NA)) +
  scale_y_continuous(breaks = (tylab - 3), labels = tylab, limits = c(-0.5, 1.5)) +
  labs(x = "Inclination", y = "Ellenberg light value\n(community mean)",
       title = "(B) Species gains") 
multiplot(ploss, pgain, cols = 2)
```
