---
title: "Appendix A: Colonization probability and local survival along the gradient"
toc: no
output:
  bookdown::pdf_document2
---

```{r settings, echo = FALSE, message=FALSE, cache=FALSE}
source("R/Settings.R")
```

# Introduction and mehtods {-}
Add text to explain the ideas and methods.

# Results {-}

```{r Tplot, fig.cap="Colonization (a) and local survival (b) of low temperature species (Ellenberg T = 2; red line) and high temperature species (Ellengerg T = 4) species along the temperature gradient. Given are means and 95\\%-Credible Intervals from logistic linear mixed models."}
X <- seq(0, 10, 0.2)
Xsd <- (X - 5) 

# Colonization
mod <- glmer(Occ ~ Temperature * T + (1|aID_SP) + (1|aID_STAO), data = coldat, family = binomial)
simdat <- arm::sim(mod, nsim)@fixef
post <- map(1:nsim, getposterior)
res <- rbind(compileres("EL = 2"), compileres("EL = 4"))
p1 <- ggplot(res, aes(x = X, y = mean, colour = value, shape = value)) +
  geom_ribbon(aes(ymin = low, ymax = high), fill = "black", col = "white", alpha = 0.2) +
  geom_line() +
    labs(title = "(A) Colonization", 
         y = "Colonization probability", 
         x = "Temperature gradient")

# Local survival
mod <- glmer(Occ ~ Temperature * T + (1|aID_SP) + (1|aID_STAO), data = survdat, family = binomial)
simdat <- arm::sim(mod, nsim)@fixef
post <- map(1:nsim, getposterior)
res <- rbind(compileres("EL = 2"), compileres("EL = 4"))
p2 <- ggplot(res, aes(x = X, y = mean, colour = value, shape = value)) +
  geom_ribbon(aes(ymin = low, ymax = high), fill = "black", col = "white", alpha = 0.2) +
  geom_line() +
    labs(title = "(B) Local survival", 
         y = "Local survival probability", 
         x = "Temperature gradient")
multiplot(p1, p2, cols = 2)
```





```{r Tplot, fig.cap="\\textit{Average Ellenberg value for \\textbf{temperature} of lost (A) and newly appearing (B) species compared to the same number of species that were randomly selected from all species recorded at the sample site (i.e. random communities). Crosses indicate the community mean of lost and newly appearing species; the grey vertical lines indicate the range of the 5\\% and 95\\% quantiles of community means calculated from the 1000 random communities for each site. The curves show the regression lines with third order polynomials for the community means of lost and newly appearing species (black solid lines) and for the average community means of random communities (orange dotted lines).}"}
# Make calculations and plot for Ellenberg T value
tres <- makesim(EL = "T", gain = FALSE, sitem = "Temperature")
txlab <- seq(0, 100, 10)
tylab <- seq(1, 5, 0.5)
ploss <- ggplot(tres, aes(x = Sitemeasure, y = meanreal)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), lwd = 0.5, colour = "grey80") +
  geom_point(shape = 4, colour = "black", cex = 2) +
  stat_smooth(method = "lm", formula = y ~ poly(x, 3), se = FALSE, col = "black") +
  stat_smooth(aes(y = mean), method = "lm", formula = y ~ poly(x,3), se = FALSE, col = "orange", lty = 2) +
  scale_x_continuous(breaks = (txlab - 50) / 10, labels = txlab / 10, limits = c(-1, NA)) +
  scale_y_continuous(breaks = (tylab - 3), labels = tylab, limits = c(-1, 1)) +
  labs(x = "Annual mean temperature", y = "Ellenberg temperature value\n(community mean)",
       title = "(A) Species losses") 
tres <- makesim(EL = "T", gain = TRUE, sitem = "Temperature")
pgain <- ggplot(tres, aes(x = Sitemeasure, y = meanreal)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), lwd = 0.5, colour = "grey80") +
  geom_point(shape = 4, colour = "black", cex = 2) +
  stat_smooth(method = "lm", formula = y ~ poly(x, 3), se = FALSE, col = "black") +
  stat_smooth(aes(y = mean), method = "lm", formula = y ~ poly(x,3), se = FALSE, col = "orange", lty = 2) +
  scale_x_continuous(breaks = (txlab - 50) / 10, labels = txlab/10, limits = c(-1, NA)) +
  scale_y_continuous(breaks = (tylab - 3), labels = tylab, limits = c(-1, 1)) +
  labs(x = "Annual mean temperature", y = "Ellenberg temperature value\n(community mean)",
       title = "(B) Species gains") 
multiplot(ploss, pgain, cols = 2)
```

`